wandb_version: 1

C:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    cli_version: 0.8.28
    is_jupyter_run: true
    python_version: 3.6.3
penalty:
  desc: null
  value: l1
tol:
  desc: null
  value: 0.001
